### ISSUE TITLE
pdf takes too long to load after i added table implementation

### ISSUE THREAD

**Issue by BendrissM** [Chagall/react-pdf-table-example#2] opened 2021-03-25 10:07 UTC
i'm using the `PDFDownloadLink` , before it was loading for like 2 sec and then i was able to download pdf, now after i added the table , it takes around 30 sec to load he file, is it just me, or it's a known issue when creating a table ?

**Comment by Chagall** [comment] 2021-03-25 13:08
Is it taking 30 sec to load the example from this repository, or is your table more complex? With this simple example it shouldn't take 30 sec to load. If you can show me an example of your code I can take a look and see what's wrong.

**Comment by BendrissM** [comment] 2021-03-25 13:18
no i literally just copy pasted your code, i had some images in the file, but it didn't take as much time, now after adding the code for the table, and after updaing it for my needs, since i only needed two columns, it's taking like 7secs to load, is it normal ?
i did some research and i was old that maybe since i'm using umi.js it's a bit slow i'm not quite sure.
```
import React from 'react';
import { Document, Page, Image, Text, StyleSheet, View } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  imageLogo: {
    marginLeft: 360,
    marginVertical: 15,
    height: 55,
    width: 120,
  },
  imageChart: {
    marginTop: 20,
    // marginHorizontal: 100,
  },
  title: {
    fontSize: 24,
    textAlign: 'left',
    marginTop: 30,
  },
  text: {
    margin: 12,
    fontSize: 14,
    textAlign: 'justify',
  },
  pageStyle: {
    paddingTop: 16,
    paddingHorizontal: 60,
    paddingBottom: 56,
  },
  tableStyle: {
    marginTop: 40,
    display: 'table',
    width: 'auto',
  },
  tableRowStyle: {
    flexDirection: 'row',
    borderStyle: 'solid',
    borderColor: '#e8e8e8',
    borderBottomWidth: 1,
  },
  firstTableColHeaderStyle: {
    width: '50%',
    borderStyle: 'solid',
    borderColor: '#000',
    borderBottomColor: '#000',
    borderWidth: 0,
    backgroundColor: '#f5f5f5',
  },
  tableColHeaderStyle: {
    width: '50%',
    borderStyle: 'solid',
    borderColor: '#000',
    borderBottomColor: '#000',
    borderWidth: 0,
    borderLeftWidth: 0,
    backgroundColor: '#f5f5f5',
  },
  firstTableColStyle: {
    width: '50%',
    borderStyle: 'solid',
    borderColor: '#000',
    borderWidth: 0,
    borderTopWidth: 0,
  },
  tableColStyle: {
    width: '50%',
    borderStyle: 'solid',
    borderColor: '#000',
    borderWidth: 0,
    borderLeftWidth: 0,
    borderTopWidth: 0,
  },
  tableCellHeaderStyle: {
    textAlign: 'center',
    margin: 4,
    fontSize: 8,
    fontWeight: 'bold',
    color: '#222222',
  },
  tableCellStyle: {
    textAlign: 'center',
    margin: 5,
    fontSize: 8,
    color: '#545454',
  },
  footer: {
    position: 'absolute',
    fontSize: 7,
    bottom: 30,
    paddingTop: 10,
    width: '100%',
    borderStyle: 'solid',
    borderColor: '#d9d9d9',
    borderTopWidth: 1.5,
    left: 60,
    right: 0,
    textAlign: 'center',
    color: '#b2b2b2',
  },
});

const SurveyReportDocument = ({ chart, logo, data, radarName }) => {
  const createTableHeader = () => {
    return (
      <View style={styles.tableRowStyle} fixed>
        <View style={styles.firstTableColHeaderStyle}>
          <Text style={styles.tableCellHeaderStyle}>Category</Text>
        </View>

        <View style={styles.tableColHeaderStyle}>
          <Text style={styles.tableCellHeaderStyle}>Score</Text>
        </View>
      </View>
    );
  };

  const createTableRow = (score, category) => {
    return (
      <View style={styles.tableRowStyle}>
        <View style={styles.firstTableColStyle}>
          <Text style={styles.tableCellStyle}>{category}</Text>
        </View>

        <View style={styles.tableColStyle}>
          <Text style={styles.tableCellStyle}>{score}</Text>
        </View>
      </View>
    );
  };

  const removeDuplicatesBy = (keyFn, array) => {
    const mySet = new Set();
    return array.filter(x => {
      const key = keyFn(x);
      const isNew = !mySet.has(key);
      if (isNew) mySet.add(key);
      return isNew;
    });
  };

  return (
    <Document>
      <Page style={styles.pageStyle} size="A4" orientation="portrait">
        <Image style={styles.imageLogo} src={logo} fixed />
        <Text style={styles.title}>{radarName}</Text>
        <Image
          style={styles.imageChart}
          src={chart?.get('canvas')._cfg.el.toDataURL('image/png')}
        />
        <View style={styles.tableStyle}>
          {createTableHeader()}
          {removeDuplicatesBy(x => x.category, data).map(({ categoryscore, category }) =>
            createTableRow(categoryscore, category)
          )}
        </View>
      </Page>
    </Document>
  );
};

export default SurveyReportDocument;

```

**Comment by Chagall** [comment] 2021-03-25 13:41
Looking at your code I would guess that either this map here:

 ```
{removeDuplicatesBy(x => x.category, data).map(({ categoryscore, category }) =>
    createTableRow(categoryscore, category)
)}
```
or the image loading at here:

` src={chart?.get('canvas')._cfg.el.toDataURL('image/png')}`

Might be the causes of the slow loading. Specially the map function. In a PDF document at my work I had to add a map to to get some table rows like you did, after I added it the document took significantly longer to render. I think there might be a better way to do this without the map, but I was too lazy to try to change it, since it was working.

I would also suggest you add this console.log to your pdf download link and see how many times "Render triggered" appears on your console. If it is 2-3 times it's fine. If it's more then you are probably re-rendering the pdf multiple times, which might be causing a slow:

```
    <PDFDownloadLink
      document={<TableDocument />}
      fileName="test.pdf">
      {({ loading }) => {
        if (loading) {
          console.log("Render triggered");
          return "Loading...";
        }
        else {
          return "Save PDF";
        }
      }}
    </PDFDownloadLink>
```

**Comment by BendrissM** [comment] 2021-03-25 15:07
i actually had that problem even before i added the map, i only had your exact code, and i tried logging how many times it gets re-rendered, and it only showed 1 time, which leaves the base64 image, but when i removed the table view, the pdf loaded fairly quickly, once i added it again, it went back to loading after 5-6 secs approximately, i'm just not sure if his load time is normal or not.

**Comment by Chagall** [comment] 2021-03-25 15:54
Well I don't know how much I can help you then. I tested the example here using the PDFDownloadLink instead of the PDFViwewe and the pdf was ready to download almost instantaneously. My PC is not that good, so I believe the problem might be somewhere else in your code.

**Comment by Chagall** [comment] 2021-03-25 16:18
By the way, how many elements does your `data` array have? If you are rendering a lot of rows, then it is normal to take (5-6s) for the pdf to be ready to download. The react-pdf library works as intented, but I noticed it's not lightning fast.

**Comment by BendrissM** [comment] 2021-03-25 16:29
that's the problem, i just render a table of 2 columns and 5 rows, i still think it's related to umi.js, i'll need to investigate this problem more, but for now, i guess 5 secs, is not that bad.

**Comment by Chagall** [comment] 2021-03-25 17:35
Yeah, I know it sucks, but taking 5 secs to load and work is better than not working at all hahaha.

**Comment by Chagall** [comment] 2021-03-31 13:32
@BendrissM Did you find out what was causing the problem?

**Comment by Chagall** [comment] 2021-04-08 02:18
I will close this now as I think you probably have moved on with your solution, and I'm pretty sure it's not a problem with this project itself.

**Closed as completed by Chagall** 2021-04-08 02:18 UTC
